<?php echo $this->render('header.phtml'); ?>


    <script src="https://cdn.pubnub.com/sdk/javascript/pubnub.4.10.0.js"></script>
    <script type="text/javascript" src="/public/js/PubNub.js"></script>
    <script type="text/javascript" src="/public/js/parser.js"></script>
    <script type="text/javascript">

        $(document).ready(function(){
            startParsing();
        });

    </script>

    <h1><?php echo $this->escape($this->title); ?></h1>
    <h2>По <strong id="searchline"><?php echo $this->escape($this->query) ?></strong></h2>
    <h3 id="status">Processing</h3>
    <div id="ajax"></div>

<?php echo $this->render('footer.phtml'); ?>